name: main
on:
  push:
  pull_request:
jobs:
  flambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.4.14.0+options,ocaml-option-flambda,dns,base64,cstruct
          dune-cache: true
      - run: echo "(lang dune 3.0)" > dune-project && opam exec -- dune build @all
